# Generated by Django 6.0.4 on 2026-05-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_type', models.CharField(choices=[('SCEP', 'SCEP'), ('MANUFACTURER', 'Producent'), ('DISTRIBUTOR', 'Dystrybutor'), ('SERVICE_CENTER', 'Serwis Zewnętrzny'), ('B2B_CLIENT', 'Klient Firmowy')], default='SERVICE_CENTER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('is_warranty', models.BooleanField(default=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Otwarte'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_COMPONENTS', 'Czekające na części'), ('DISASSEMBLY', 'Oczekuja na demontaż'), ('READY_FOR_PICKUP', 'Gotowe do odbioru'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('NOT_REPAIRABLE', 'Nie do naprawy'), ('CLOSED', 'Zamknięte')], default='OPEN', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('business_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.customer')),
            ],
        ),
    ]
