# Generated by Django 6.0.4 on 2026-04-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_type', models.CharField(choices=[('MANUFACTURER', 'Producent'), ('DISTRIBUTOR', 'Dystrybutor'), ('SERVICE_CENTER', 'Serwis Zewnętrzny'), ('B2B_CLIENT', 'Klient Firmowy')], default='SERVICE_CENTER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('moq', models.PositiveIntegerField(default=1)),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'MANUFACTURER'}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.ForeignKey(limit_choices_to={'partner_type': 'MANUFACTURER'}, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('is_warranty', models.BooleanField(default=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='after_sales.customer')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('storage_location', models.CharField(blank=True, max_length=10, null=True)),
                ('plant', models.CharField(blank=True, max_length=10, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.component')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.component')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='after_sales.serviceticket')),
            ],
        ),
    ]
