# Generated by Django 6.0.4 on 2026-05-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('after_sales', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.devicemodel'),
        ),
        migrations.AddField(
            model_name='ticketcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.component'),
        ),
        migrations.AddField(
            model_name='ticketcomponent',
            name='ticket_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.serviceticket'),
        ),
    ]
