# Generated by Django 6.0.4 on 2026-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='device_category',
            field=models.CharField(choices=[('TV', 'Telewizor'), ('Audio', 'Audio'), ('SAS', 'SAS/SDA'), ('Ebike', 'Rower elektryczny'), ('Escooter', 'Hulajnoga elektryczna')], max_length=200, null=True),
        ),
    ]
