# Generated by Django 6.0.4 on 2026-04-10 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otwarte'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_COMPONENTS', 'Czekające na części'), ('READY_FOR_PICKUP', 'Gotowe do odbioru'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('NOT_REPAIRABLE', 'Nie do naprawy'), ('CLOSED', 'Zamknięte')], default='OPEN', max_length=100),
        ),
    ]
