# Generated by Django 6.0.4 on 2026-04-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0002_devicemodel_device_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sn_need', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.componentcategory'),
        ),
    ]
