# Generated by Django 6.0.4 on 2026-05-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0003_remove_businesspartner_tax_id_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='margin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.margin'),
        ),
    ]
