# Generated by Django 6.0.4 on 2026-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0003_componentcategory_component_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otwarte'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_COMPONENTS', 'Czekające na części'), ('DISSASEMBLY', 'Oczekuja na demontaż'), ('READY_FOR_PICKUP', 'Gotowe do odbioru'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('NOT_REPAIRABLE', 'Nie do naprawy'), ('CLOSED', 'Zamknięte')], default='OPEN', max_length=100),
        ),
    ]
