# Generated by Django 6.0.4 on 2026-05-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0004_alter_businesspartner_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='main_branch',
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='business_partner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner'),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='is_main_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='parts_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='parts_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='service_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='service_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnerbranch',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
