# Generated by Django 6.0.4 on 2026-04-28 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0004_alter_serviceticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='business_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.customer'),
        ),
        migrations.AlterField(
            model_name='ticketcomponent',
            name='ticket_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.serviceticket'),
        ),
    ]
