# Generated by Django 6.0.4 on 2026-04-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0005_serviceticket_business_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='partner_type',
            field=models.CharField(choices=[('SCEP', 'Sharp Consumer Electronics Poland sp. z o.o.'), ('MANUFACTURER', 'Producent'), ('DISTRIBUTOR', 'Dystrybutor'), ('SERVICE_CENTER', 'Serwis Zewnętrzny'), ('B2B_CLIENT', 'Klient Firmowy')], default='SERVICE_CENTER', max_length=20),
        ),
    ]
