# Generated by Django 6.0.4 on 2026-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0005_remove_businesspartner_main_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='partner_type',
            field=models.CharField(choices=[('SCEP', 'SCEP'), ('MANUFACTURER', 'Producent'), ('DISTRIBUTOR', 'Dystrybutor'), ('SERVICE_CENTER', 'Serwis Zewnętrzny'), ('B2B_CLIENT', 'Klient Firmowy'), ('CARRIER', 'Przewoźnik')], default='SERVICE_CENTER', max_length=20),
        ),
    ]
