# Generated by Django 6.0.4 on 2026-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0006_serviceticket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='partner_type',
            field=models.CharField(choices=[('SCEP', 'SCEP'), ('MANUFACTURER', 'Producent'), ('DISTRIBUTOR', 'Dystrybutor'), ('SERVICE_CENTER', 'Serwis Zewnętrzny'), ('B2B_CLIENT', 'Klient Firmowy')], default='SERVICE_CENTER', max_length=20),
        ),
    ]
