# Generated by Django 6.0.4 on 2026-04-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0007_stock_vendor_alter_businesspartner_partner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='name',
        ),
    ]
