# Generated by Django 6.0.4 on 2026-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0008_remove_component_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='fg_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
