# Generated by Django 6.0.4 on 2026-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0009_rename_name_devicemodel_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='ticket_number',
            field=models.CharField(max_length=50),
        ),
    ]
