# Generated by Django 6.0.4 on 2026-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0010_alter_serviceticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='part_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='fg_code',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otwarte'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_COMPONENTS', 'Czekające na części'), ('DISASSEMBLY', 'Oczekuja na demontaż'), ('READY_FOR_PICKUP', 'Gotowe do odbioru'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('NOT_REPAIRABLE', 'Nie do naprawy'), ('CLOSED', 'Zamknięte')], default='OPEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='ticket_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
