# Generated by Django 6.0.4 on 2026-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0011_alter_component_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='fg_code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
