# Generated by Django 6.0.4 on 2026-05-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('after_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sn_need', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('moq', models.PositiveIntegerField(default=1)),
                ('manufacturer', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'MANUFACTURER'}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.componentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=150)),
                ('device_category', models.CharField(choices=[('TV', 'Telewizor'), ('Audio', 'Audio'), ('SAS', 'SAS/SDA'), ('Ebike', 'Rower elektryczny'), ('Escooter', 'Hulajnoga elektryczna')], max_length=200, null=True)),
                ('manufacturer', models.ForeignKey(limit_choices_to={'partner_type': 'MANUFACTURER'}, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('storage_location', models.CharField(blank=True, max_length=10, null=True)),
                ('plant', models.CharField(blank=True, max_length=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.component')),
            ],
        ),
    ]
