# Generated by Django 6.0.4 on 2026-05-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('after_sales', '0006_alter_businesspartner_partner_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartnerbranch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('tracking', models.CharField(max_length=30)),
                ('shipment_date', models.DateField()),
                ('delivery_Date', models.DateField()),
                ('comment', models.TextField()),
                ('parcel_type', models.CharField(choices=[('PARCEL', 'Paczka'), ('PALLET', 'Paleta')])),
                ('size', models.CharField(choices=[('SMALL', 'Mała'), ('MEDIUM', 'Średnia'), ('BIG', 'Duża')])),
                ('dimensions', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=10)),
                ('carrier_document', models.CharField(max_length=50)),
                ('customs_document', models.CharField(max_length=50)),
                ('packing_list', models.CharField(max_length=50)),
                ('fv_proforma', models.CharField(max_length=50)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartnerbranch')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
