# Generated by Django 6.0.4 on 2026-04-29 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('after_sales', '0006_serviceticket_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_COMPONENTS', 'Czekające na części'), ('DISSASEMBLY', 'Oczekuje na demontaż'), ('PR', 'Oczekuje na Panel Repair'), ('READY_FOR_PICKUP', 'Gotowe do odbioru'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('NOT_REPAIRABLE', 'Nie do naprawy'), ('NOT_PROFITABLE', 'Naprawa nieopłacalna'), ('CLOSED', 'Zamknięte')], default='NEW')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(choices=[('IN_WARRANTY', 'Gwarancja'), ('OUT_OF_WARRANTY', 'Poza gwarancją'), ('BUFFER', 'Buffer')], default='IN_WARRANTY')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=50, null=True)),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('qty_to_be_realized', models.IntegerField()),
                ('internal_order_number', models.CharField()),
                ('material_prepared', models.CharField(max_length=50, null=True)),
                ('qty_prepared', models.IntegerField()),
                ('comment', models.TextField()),
                ('comment_for_tpm', models.TextField()),
                ('fulfillment_start_date', models.DateField()),
                ('fulfillment_comment', models.CharField(max_length=255)),
                ('fulfillment_finish_date', models.DateField()),
                ('material_price_pln', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_price_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('article_number', models.CharField(max_length=50)),
                ('original_article_number', models.CharField(max_length=50)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.serviceticket')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('serial_number_scep', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=50)),
                ('shipment_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('parcel_type', models.CharField(choices=[('PACKAGE', 'Paczka'), ('PALLET', 'Paleta')])),
                ('size', models.CharField()),
                ('dimensions', models.CharField()),
                ('weight', models.CharField()),
                ('carrier_documents', models.CharField()),
                ('customs_documents', models.CharField()),
                ('packing_list', models.CharField()),
                ('fv_proforma', models.CharField()),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartner')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.orderstracking'),
        ),
    ]
