# Generated by Django 6.0.4 on 2026-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty_to_be_realized',
            field=models.IntegerField(null=True),
        ),
    ]
