# Generated by Django 6.0.4 on 2026-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_qty_to_be_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='material_price_eur',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='material_price_pln',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty_prepared',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty_to_be_realized',
            field=models.IntegerField(auto_created=models.IntegerField()),
        ),
    ]
