# Generated by Django 6.0.4 on 2026-05-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0005_remove_businesspartner_main_branch_and_more'),
        ('orders', '0002_alter_orders_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorders',
            name='business_partner_branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='after_sales.businesspartnerbranch'),
        ),
        migrations.AddField(
            model_name='orders',
            name='business_partner_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='after_sales.businesspartnerbranch'),
        ),
    ]
