# Generated by Django 6.0.4 on 2026-05-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
        ('orders', '0003_historicalorders_business_partner_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='logistic.shipment'),
        ),
        migrations.AlterField(
            model_name='historicalorders',
            name='tracking',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistic.shipment'),
        ),
        migrations.DeleteModel(
            name='OrdersTracking',
        ),
    ]
