# Generated by Django 6.0.4 on 2026-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_material_price_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty_to_be_realized',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
