# Generated by Django 6.0.4 on 2026-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_qty_to_be_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty_to_be_realized',
            field=models.IntegerField(default=0),
        ),
    ]
