# Generated by Django 6.0.4 on 2026-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_qty_to_be_realized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comment_for_tpm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fulfillment_finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fulfillment_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='internal_order_number',
            field=models.CharField(null=True),
        ),
    ]
