# Generated by Django 6.0.4 on 2026-04-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_comment_alter_orders_comment_for_tpm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders.orderstracking'),
        ),
    ]
