# Generated by Django 6.0.4 on 2026-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='internal_order_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
