# Generated by Django 6.0.4 on 2026-04-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_internal_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='article_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='comment_for_tpm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fulfillment_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fulfillment_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fulfillment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='material_prepared',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='original_article_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders.orderstracking'),
        ),
        migrations.AlterField(
            model_name='ordersserialnumber',
            name='serial_number_scep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='carrier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='carrier_documents',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='customs_documents',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='dimensions',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='fv_proforma',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='packing_list',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='parcel_type',
            field=models.CharField(blank=True, choices=[('PACKAGE', 'Paczka'), ('PALLET', 'Paleta')], null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowa'), ('ORDERED', 'Zlecona'), ('DELIVERED', 'Dostarczona')], default='NEW'),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='tracking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderstracking',
            name='weight',
            field=models.CharField(blank=True, null=True),
        ),
    ]
