# Generated by Django 6.0.4 on 2026-04-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_article_number_alter_orders_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty_prepared',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='qty_to_be_realized',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
