# Generated by Django 6.0.4 on 2026-05-08 11:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0012_alter_devicemodel_fg_code'),
        ('orders', '0010_alter_orders_qty_alter_orders_qty_prepared_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrders',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_COMPONENTS', 'Czekające na części'), ('DISSASEMBLY', 'Oczekuje na demontaż'), ('PR', 'Oczekuje na Panel Repair'), ('READY_FOR_PICKUP', 'Gotowe do odbioru'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('NOT_REPAIRABLE', 'Nie do naprawy'), ('NOT_PROFITABLE', 'Naprawa nieopłacalna'), ('CLOSED', 'Zamknięte')], default='NEW')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(choices=[('IN_WARRANTY', 'Gwarancja'), ('OUT_OF_WARRANTY', 'Poza gwarancją'), ('BUFFER', 'Buffer')], default='IN_WARRANTY')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_to_be_realized', models.PositiveIntegerField(default=0)),
                ('internal_order_number', models.CharField(blank=True, null=True)),
                ('material_prepared', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_prepared', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_for_tpm', models.TextField(blank=True, null=True)),
                ('fulfillment_start_date', models.DateField(blank=True, null=True)),
                ('fulfillment_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('fulfillment_finish_date', models.DateField(blank=True, null=True)),
                ('material_price_pln', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('material_price_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('article_number', models.CharField(blank=True, max_length=50, null=True)),
                ('original_article_number', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business_partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='after_sales.businesspartner')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='after_sales.serviceticket')),
                ('tracking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.orderstracking')),
            ],
            options={
                'verbose_name': 'historical orders',
                'verbose_name_plural': 'historical orderss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
